const AUTH_TYPES = {
  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  LOGOUT: 'USER_LOGOUT',
  LOAD_PROFILE: 'USER_LOAD_PROFILE'
};

export default AUTH_TYPES
