const CHANNEL_TYPES = {
  CHANNEL_REQUEST: 'CHANNEL_REQUEST',
  CHANNEL_SUCCESS: 'CHANNEL_SUCCESS',
  CHANNEL_FAILURE: 'CHANNEL_FAILURE',
  
  CHANNEL_BY_ID_REQUEST: 'CHANNEL_BY_ID_REQUEST',
  CHANNEL_BY_ID_SUCCESS: 'CHANNEL_BY_ID_SUCCESS',
  CHANNEL_BY_ID_FAILURE: 'CHANNEL_BY_ID_FAILURE',
};

export default CHANNEL_TYPES
